name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas==2.2.3 ruff
        
    - name: Run ruff linter
      run: |
        echo "Running ruff linter..."
        ruff check execute.py --output-format=full || true
        echo "Ruff linting complete."
        
    - name: Execute Python script
      run: |
        echo "Executing execute.py..."
        python execute.py > result.json
        echo "Script execution complete."
        cat result.json
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Prepare artifacts for deployment
      run: |
        mkdir -p _site
        cp result.json _site/
        echo '<!DOCTYPE html><html><head><title>Results</title></head><body><h1>Analysis Results</h1><pre id="json"></pre><script>fetch("result.json").then(r=>r.json()).then(d=>document.getElementById("json").textContent=JSON.stringify(d,null,2))</script></body></html>' > _site/index.html
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '_site'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4